baseURL = 'http://blog.kosodatepapa.jp/'
languageCode = 'ja'
title = 'kosodatepapaブログ'
theme = "mainroad"
defaultContentLanguage = "ja"
hasCJKLanguage = true
mainSections = ["post"]
publishDir = "../docs"
